### ISSUE TITLE
char_arrays

### ISSUE THREAD

**Issue by aeosynth** [Biribiri/K-R#2]
1. https://github.com/Biribiri/K-R/blob/master/C/Ch.1/char_arrays.c#L2
   
   ```
   #define MAXLINE 10
   ```
   
   really? your lines only go up to ten characters? that's a really small line.
2. https://github.com/Biribiri/K-R/blob/master/C/Ch.1/char_arrays.c#L13
   
   ```
   while((len = getlin(line, MAXLINE)) > 0){
   ```
   
   I know the book uses this, but it's shit - if you type some characters and then hit EOF, the `getlin` loop terminates, but this while loop doesn't. hitting EOF should terminate the entire program immediately IMO.
3. https://github.com/Biribiri/K-R/blob/master/C/Ch.1/char_arrays.c#L22
   
   ```
   printf("%s", longest);
   ```
   
   again you don't print a final newline. I don't know about you, but that feels a bit sloppy to me.
4. https://github.com/Biribiri/K-R/blob/master/C/Ch.1/char_arrays.c#L33-34
   
   ```
   line[i] = c;
   ++i;
   ```
   
   could be merged into
   
   ```
   line[i++] = c;
   ```

**Comment by Biribiri** [comment]
HAHA that was to test reverse(), and too see what happened when I exceeded MAXLINE; it's easier to write 10 char than 10000.

I thought the same thing, but for this I found doing getline() in the conditional check to be better than in the while loop just because the way it's setup.

I didn't do a print a newline because the array will always have a '\n' before '\0'
